### ISSUE TITLE
admin on RC server is throwing 500s

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1606]
When I try access a channel object in the admin on RC, I get a 500 error. For example, at /admin/channels/channel/12097/change/

I haven't been able to locate the stack trace yet.

**Comment by rhysyngsun** [comment]
```
2018-12-26T21:23:34.791685+00:00 app[web.2]: Traceback (most recent call last):
2018-12-26T21:23:34.791687+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 96, in inner
2018-12-26T21:23:34.791689+00:00 app[web.2]: return func(*args, **kwargs)
2018-12-26T21:23:34.791691+00:00 app[web.2]: psycopg2.OperationalError: cursor "_django_curs_140009692722944_1" does not exist
2018-12-26T21:23:34.791693+00:00 app[web.2]: 
2018-12-26T21:23:34.791694+00:00 app[web.2]: 
2018-12-26T21:23:34.791696+00:00 app[web.2]: The above exception was the direct cause of the following exception:
2018-12-26T21:23:34.791697+00:00 app[web.2]: 
2018-12-26T21:23:34.791699+00:00 app[web.2]: Traceback (most recent call last):
2018-12-26T21:23:34.791701+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1466, in cursor_iter
2018-12-26T21:23:34.791703+00:00 app[web.2]: for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
2018-12-26T21:23:34.791726+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1466, in <lambda>
2018-12-26T21:23:34.791729+00:00 app[web.2]: for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
2018-12-26T21:23:34.791730+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 96, in inner
2018-12-26T21:23:34.791732+00:00 app[web.2]: return func(*args, **kwargs)
2018-12-26T21:23:34.791734+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
2018-12-26T21:23:34.791736+00:00 app[web.2]: raise dj_exc_value.with_traceback(traceback) from exc_value
2018-12-26T21:23:34.791737+00:00 app[web.2]: File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 96, in inner
2018-12-26T21:23:34.791739+00:00 app[web.2]: return func(*args, **kwargs)
2018-12-26T21:23:34.791740+00:00 app[web.2]: django.db.utils.OperationalError: cursor "_django_curs_140009692722944_1" does not exist
```

**Comment by rhysyngsun** [comment]
Working theory is that this error is being caused trying to generate a widgetlist dropdown for the huge number of channels we have (meaning we have a huge number of widget lists)
