### ISSUE TITLE
You were logged out, please login again

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1895]
We're seeing a lot of these error in sentry starting a couple of weeks ago. 

https://sentry.io/organizations/mit-office-of-digital-learning/issues/897413441/?project=216201&referrer=github_plugin

```
Stacktrace (most recent call first):

  at captureMessage (./node_modules/raven-js/src/raven.js:584:1)
  at captureException (./node_modules/raven-js/src/raven.js:508:1)
  at q._promiseRejectionHandler (./node_modules/raven-js/src/raven.js:431:1)

You were logged out, please login again
```

**Comment by pdpinch** [comment]
haven't been seeing these anymore
