### ISSUE TITLE
Many comments to a post break the `comment-list` REST API

### ISSUE THREAD

**Issue by giocalitri** [mitodl/open-discussions#239]
If there are 16 nested comments, the rest api breaks with this error:

```
web_1     | [2017-10-02 19:17:35] ERROR 16 [django.request] exception.py:124 - [9a3d41ff4fb1] - Internal Server Error: /api/v0/posts/2/comments/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1     |     response = self._get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1     |     return view_func(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1     |     return self.dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 477, in dispatch
web_1     |     response = self.handle_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 437, in handle_exception
web_1     |     self.raise_uncaught_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 474, in dispatch
web_1     |     response = handler(request, *args, **kwargs)
web_1     |   File "./channels/views.py", line 260, in get
web_1     |     users = _lookup_users_for_comments(comments)
web_1     |   File "./channels/views.py", line 237, in _lookup_users_for_comments
web_1     |     _populate_authors_for_comments(comments, author_set)
web_1     |   File "./channels/views.py", line 222, in _populate_authors_for_comments
web_1     |     _populate_authors_for_comments(comment.replies, author_set)
web_1     |   File "./channels/views.py", line 222, in _populate_authors_for_comments
web_1     |     _populate_authors_for_comments(comment.replies, author_set)
web_1     |   File "./channels/views.py", line 222, in _populate_authors_for_comments
web_1     |     _populate_authors_for_comments(comment.replies, author_set)
web_1     |   [Previous line repeated 6 more times]
web_1     |   File "./channels/views.py", line 219, in _populate_authors_for_comments
web_1     |     if comment.author:
nginx_1   | 192.168.99.1 - - [02/Oct/2017:19:17:21 +0000] "GET /api/v0/posts/2/comments/ HTTP/1.1" 500 146829 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0" "-"
web_1     | AttributeError: 'MoreComments' object has no attribute 'author'
```

**Comment by pdpinch** [comment]
This should be avoid by https://github.com/mitodl/open-discussions/issues/269

**Comment by pdpinch** [comment]
@noisecapella do you think we can we close this?
