### ISSUE TITLE
Fix errors in Travis CI output

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#335]
This isn't causing test failures, but it's annoying to have it in the output:

```
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 361, in find_app
celery_1  |     found = sym.app
celery_1  | AttributeError: module 'open_discussions' has no attribute 'app'
celery_1  | 
celery_1  | During handling of the above exception, another exception occurred:
celery_1  | 
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 366, in find_app
celery_1  |     found = sym.celery
celery_1  | AttributeError: module 'open_discussions' has no attribute 'celery'
celery_1  | 
celery_1  | During handling of the above exception, another exception occurred:
celery_1  | 
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 355, in find_app
celery_1  |     sym = symbol_by_name(app, imp=imp)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 506, in symbol_by_name
celery_1  |     return imports.symbol_by_name(name, imp=imp)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
celery_1  |     return getattr(module, cls_name) if cls_name else module
celery_1  | AttributeError: module 'open_discussions' has no attribute 'celery'
celery_1  | 
celery_1  | During handling of the above exception, another exception occurred:
celery_1  | 
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/bin/celery", line 11, in <module>
celery_1  |     sys.exit(main())
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
celery_1  |     _main()
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
celery_1  |     cmd.execute_from_commandline(argv)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celery_1  |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
celery_1  |     argv = self.setup_app_from_commandline(argv)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
celery_1  |     self.app = self.find_app(app)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
celery_1  |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 374, in find_app
celery_1  |     symbol_by_name=symbol_by_name, imp=imp,
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 358, in find_app
celery_1  |     sym = imp(app)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
celery_1  |     return imp(module, package=package)
celery_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1  |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
celery_1  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
celery_1  |   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
celery_1  |   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
celery_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
celery_1  |   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
celery_1  |   File "/src/open_discussions/celery.py", line 20, in <module>
celery_1  |     client = Client(**settings.RAVEN_CONFIG)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 53, in __getattr__
celery_1  |     self._setup(name)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
celery_1  |     self._wrapped = Settings(settings_module)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 97, in __init__
celery_1  |     mod = importlib.import_module(self.SETTINGS_MODULE)
celery_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1  |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
celery_1  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
celery_1  |   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
celery_1  |   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
celery_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
celery_1  |   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
celery_1  |   File "/src/open_discussions/settings.py", line 412, in <module>
celery_1  |     raise ImproperlyConfigured("OPEN_DISCUSSIONS_COOKIE_NAME is not set")
celery_1  | django.core.exceptions.ImproperlyConfigured: OPEN_DISCUSSIONS_COOKIE_NAME is not set
```

**Comment by noisecapella** [comment]
Maybe we should put our testing env variables in some file like `.env_test` and source it wherever we need it, in the docker containers or when we run tests
