### ISSUE TITLE
Replying to a deleted comment results in error page due to this not being possible

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#477]
Reddit doesn't allow this and raises an error. We should do a few things:

- [x] Hide the reply button if the comment was deleted
- [x] Update the API to return a non-500 error
- [x] Update the frontend to handle this new error code gracefully

This error is being raised by the reddit backend when you try to reply:

```
web_1     | praw.exceptions.APIException: DELETED_COMMENT: 'that comment has been deleted' on field 'parent'
web_1     | [2018-02-07 14:32:06] ERROR 41 [django.request] exception.py:124 - [d6d603847e3a] - Internal Server Error: /api/v0/posts/e/comments/
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
web_1     |     response = get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1     |     response = self._get_response(request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1     |     response = self.process_exception_by_middleware(e, request)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1     |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1     |     return view_func(*args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
web_1     |     return self.dispatch(request, *args, **kwargs)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 477, in dispatch
web_1     |     response = self.handle_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 437, in handle_exception
web_1     |     self.raise_uncaught_exception(exc)
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 474, in dispatch
web_1     |     response = handler(request, *args, **kwargs)
web_1     |   File "./channels/views/comments.py", line 97, in post
web_1     |     serializer.save()
web_1     |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
web_1     |     self.instance = self.create(validated_data)
web_1     |   File "./channels/serializers.py", line 420, in create
web_1     |     **kwargs
web_1     |   File "./channels/api.py", line 519, in create_comment
web_1     |     return self.get_comment(comment_id).reply(text)
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/models/reddit/mixins/replyable.py", line 16, in reply
web_1     |     return self._reddit.post(API_PATH['comment'], data=data)[0]
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/reddit.py", line 411, in post
web_1     |     return self._objector.objectify(data)
web_1     |   File "/usr/local/lib/python3.6/site-packages/praw/objector.py", line 122, in objectify
web_1     |     raise APIException(*errors[0])
web_1     | praw.exceptions.APIException: DELETED_COMMENT: 'that comment has been deleted' on field 'parent'
```

**Comment by rhysyngsun** [comment]
@pdpinch is it ok if for item 3 here, we simply pop up a toast saying "unable to reply to comment" and reload the comment data so they no longer get the reply button?

**Comment by rhysyngsun** [comment]
@pdpinch yes we do
