### ISSUE TITLE
Comment serialization doesn't work if user exists on reddit but not open-discussions

### ISSUE THREAD

**Issue by noisecapella** [mitodl/open-discussions#762]

**Comment by noisecapella** [comment]
celery_1   | Traceback (most recent call last):
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    celery_1   |     R = retval = fun(*args, **kwargs)
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    celery_1   |     return self.run(*args, **kwargs)
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 468, in run
    celery_1   |     return task._orig_run(*args, **kwargs)
    celery_1   |   File "/src/search/tasks.py", line 78, in index_post_with_comments
    celery_1   |     api.index_post_with_comments(post_id)
    celery_1   |   File "/src/search/indexing_api.py", line 172, in index_post_with_comments
    celery_1   |     chunk_size=settings.ELASTICSEARCH_INDEXING_CHUNK_SIZE,
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    celery_1   |     for ok, item in streaming_bulk(client, actions, **kwargs):
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 180, in streaming_bulk
    celery_1   |     client.transport.serializer):
    celery_1   |   File "/usr/local/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 58, in _chunk_actions
    celery_1   |     for action, data in actions:
    celery_1   |   File "/src/search/serializers.py", line 31, in serialize_post_and_comments
    celery_1   |     yield from _serialize_comment_tree(post_obj.comments)
    celery_1   |   File "/src/search/serializers.py", line 19, in _serialize_comment_tree
    celery_1   |     yield serialize_comment(comment)
    celery_1   |   File "/src/search/serializers.py", line 72, in serialize_comment
    celery_1   |     'author': comment_obj.author.name,
    celery_1   | AttributeError: 'NoneType' object has no attribute 'name'
